language: ruby
env: DEBUG=true
sudo: false

before_script:
  - bundle update

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - ruby-head
  - jruby-9.1.8.0

# ActiveSupport 4.x (5.x needs Ruby 2.2+)
matrix:
  include:
    - rvm: 2.1.9
      gemfile: Gemfile.as4
    - rvm: 2.0.0
      gemfile: Gemfile.as4
    - rvm: 1.9.3
      gemfile: Gemfile.as4
    - rvm: jruby-19mode
      gemfile: Gemfile.as4
