language: ruby
env: DEBUG=true
sudo: false

before_script:
  - bundle update

rvm:
  - 2.6.4
  - 2.5.6
  - 2.4.7
  - 2.3.7
  - 2.2.10
  - ruby-head
  - jruby-head

# ActiveSupport 4.x (5.x needs Ruby 2.2+)
matrix:
  include:
    - rvm: 2.1.10
      gemfile: Gemfile.as4
    - rvm: 2.0.0
      gemfile: Gemfile.as4
    - rvm: 1.9.3
      gemfile: Gemfile.as4
    - rvm: jruby-19mode
      gemfile: Gemfile.as4
