name: specs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        ruby: ["2.3", "2.4", "2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "head", "jruby"]
        redis: ["3.0", "4.0", "5.0"]
        exclude:
          - ruby: "2.3"
            redis: "5.0"
          - ruby: "2.4"
            redis: "5.0"

    env:
      REDIS_VERSION: "${{matrix.redis}}"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby & run Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake spec
