name: specs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby: [2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, head, jruby]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby & run Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake spec
